---
# path to .csv file for data matrix
x_path: /Users/xiaoh/Desktop/Research/EssReg_Beta/ER_Example/x_preScale.csv
# path to .csv file for response vector
y_path: /Users/xiaoh/Desktop/Research/EssReg_Beta/ER_Example/check_y.csv
# path to directory for saving results
out_path: /Users/xiaoh/Desktop/   
# number of replicates for delta cross-validation  
rep_cv: 10         
# alpha level for confidence intervals      
alpha_level: 0.05     
# false discovery rate thresholding p-value cutoff      
thresh_fdr: 0.2
# lambda
lambda: 0.1
