---
# path to .csv file for data matrix
x_path: /Users/xiaoh/Desktop/Research/EssReg_Beta/ER_Example/x_preScale.csv
# path to .csv file for response vector
y_path: /Users/xiaoh/Desktop/Research/EssReg_Beta/ER_Example/check_y.csv
# path to directory for saving results
out_path: /Users/xiaoh/Desktop/
# number of folds for cross-validation   
k: 4
# number of replicates for cross-validation
nreps: 3
# is y categorical?
y_factor: FALSE
# select optimal parameter values by correlation?
sel_corr: TRUE
# permutation test type
perm_option: "y"
# type of beta estimation - can be LS or NULL          
beta_est: LS     
# find confidence intervals for betas?         
conf_int: TRUE          
# estimate responses (do prediction)?  
pred: TRUE
# number of replicates for cross-validation  
rep_cv: 5        
# diagonal structure of data matrix?       
diagonal: FALSE   
# use intersection (FALSE) or union (TRUE) for merging        
merge: FALSE   
# do columns of data matrix have equal variance?           
equal_var: FALSE   
# alpha level for confidence intervals      
alpha_level: 0.05   
# literally no idea what this is      
support: NULL    
# do multiple testing correction?         
correction: TRUE      
# include print statements?       
verbose: TRUE      
# false discovery rate thresholding p-value cutoff      
thresh_fdr: 0.2
# other threshold
thresh: 0.001
# lambda, should be multiple values for step 4
lambda: [0.1, 0.5, 1] 
# change entire row/column for important variables?          
change_all: FALSE
# The best delta chosen from step 1 and step 2. If running step 3, a fine grid will be constructed.
best_delta: 0.001
# If NULL, a fine grid will be calculated. 
delta_grid: NULL

